## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

CUDA_DIR := /misc/software-lin/lmbsoft/cuda-7.0.28

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_52,code=sm_52 \
             -gencode arch=compute_52,code=compute_52

BLAS := atlas

# MATLAB_DIR := /misc/software-lin/matlabR2015a

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
PYTHON_INCLUDE := /usr/include/python2.7 \
                  /usr/lib/python2.7/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
PYTHON_LIB := /usr/lib

# Uncomment to support layers written in Python (will link against Python libs)
WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE)
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

SYS_INCLUDE_DIRS := \
  /misc/lmbraid17/sceneflownet/common/software-root/include \
  /misc/software-lin/lmbsoft/cudnn-7.0-linux-x64-v3.0/include \
  /misc/software-lin/lmbsoft/boost_1_56_0/ \
  /misc/software-lin/lmbsoft/glog/include \
  /misc/software-lin/lmbsoft/gflags-2.1.1/build/include \
  /misc/software-lin/lmbsoft/mdb-mdb/libraries/liblmdb \
  $(PYTHON_INCLUDE) \
  /usr/local/include

LIBRARY_DIRS := \
  /misc/lmbraid17/sceneflownet/common/software-root/lib \
  /misc/software-lin/lmbsoft/cuda-7.0.28/lib64 \
  /misc/software-lin/lmbsoft/cudnn-7.0-linux-x64-v3.0/lib64 \
  /misc/software-lin/lmbsoft/boost_1_56_0/stage/lib \
  /misc/software-lin/lmbsoft/glog/lib \
  /misc/software-lin/lmbsoft/gflags-2.1.1/build/lib \
  /misc/software-lin/lmbsoft/mdb-mdb/libraries/liblmdb \
  $(PYTHON_LIB) \
  /usr/local/lib

LDFLAGS += -Wl,-rpath,/misc/software-lin/lmbsoft/boost_1_56_0/stage/lib \
-Wl,-rpath,/misc/lmbraid17/sceneflownet/common/software-root/lib \
-Wl,-rpath,/misc/software-lin/lmbsoft/glog/lib \
-Wl,-rpath,/misc/software-lin/lmbsoft/gflags-2.1.1/build/lib \
-Wl,-rpath,/misc/software-lin/lmbsoft/mdb-mdb/libraries/liblmdb \
-Wl,-rpath,/misc/software-lin/lmbsoft/cuda-7.0.28/lib64 \
-Wl,-rpath,/misc/software-lin/lmbsoft/cudnn-7.0-linux-x64-v3.0/lib64

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging.
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @
